openapi: 3.2.0
info:
  title: Optical Character Recognition Custodians API
  description: The Optical Character Recognition API enables you to extract information from portfolio statements that are formatted as PDFs or images.
  version: 1.0.0
servers:
- url: ' https://www.us-api.morningstar.com/optical-character-recognition/v1'
security:
- bearerAuth: []
tags:
- name: Custodians
paths:
  /custodians:
    get:
      tags:
      - Custodians
      summary: Get custodians
      description: 'Get all custodians for the language and region specified in the `Accept-Language` header.


        The response returns the unique `documentName` and `documentShortName` values that identify custodians. At least one of these values is required when making a POST request to the `statement-details` endpoint.


        The response separates the supported custodians into two lists. The `mainCustodians` list contains custodians for whom specific processing logic has been written. The `others` list contains custodians for whom common processing logic is used and may therefore produce results with a lower degree of accuracy.'
      parameters:
      - name: Accept-Language
        in: header
        description: Language and locale
        schema:
          type: string
          enum:
          - en-US
          - en-CA
          - fr-CA
      responses:
        '200':
          description: OK
        '404':
          description: Accept-Language header values not valid.
        '500':
          description: Internal Server Error
      operationId: getCustodians
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
